### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by brycemcole**
this.log was equal to debug instead of log

typo fix

### CODE REVIEW

**Comment by brycemcole** [comment]
This should fix #44 #35

**Comment by pman193** [comment]
Hey. This is what I'm getting even after applying every fix I've found on these threads. Not a coder. Just copying and pasting. I've also noticed that since the release of the new Frigidaire app, not only is the plugin not working, but, I'm unable to control my unit it with my google home. Don't know if it's related.

[6/6/2023, 3:38:31 PM] [homebridge-frigidaire] Child bridge process ended
[6/6/2023, 3:38:31 PM] [homebridge-frigidaire] Process Ended. Code: 1, Signal: null
[6/6/2023, 3:38:38 PM] [homebridge-frigidaire] Restarting Process...
[6/6/2023, 3:38:39 PM] [homebridge-frigidaire] Launched child bridge with PID 28541
[6/6/2023, 3:38:40 PM] Registering platform 'homebridge-frigidaire.Frigidaire'
[6/6/2023, 3:38:40 PM] [homebridge-frigidaire] Loaded homebridge-frigidaire v2.1.3 child bridge successfully
failed to parse auth result json: '[object Object]'

/usr/lib/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:539
var sessionKey = body.data.sessionKey
^
TypeError: Cannot read properties of undefined (reading 'sessionKey')
at Request.authPostCallback [as _callback] (/usr/lib/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:539:37)
at Request.self.callback (/usr/lib/node_modules/homebridge-frigidaire/node_modules/request/request.js:185:22)
at Request.emit (node:events:513:28)
at Request. (/usr/lib/node_modules/homebridge-frigidaire/node_modules/request/request.js:1154:10)
at Request.emit (node:events:513:28)
at IncomingMessage. (/usr/lib/node_modules/homebridge-frigidaire/node_modules/request/request.js:1076:12)
at Object.onceWrapper (node:events:627:28)
at IncomingMessage.emit (node:events:525:35)
at endReadableNT (node:internal/streams/readable:1359:12)
at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by pman193** [comment]
It's all working after adding and editing all the changes in these posts. Final step was changing my password in the app to get it to work.

**Comment by brycemcole** [comment]
@pman193 hey could you give the exact changes that you implemented?

**Comment by pman193** [comment]
It was a lot. I got the lines of code that needed to be changed from like 4 different peoples commits.

**Comment by pman193** [comment]
@marekbrz @amaisano Start by looking at their contributions. Also, you need to change the password in the new app to get it to work. That enables Google Home support as well.

**Pull request closed without merging**
